<h1>0. データ表示</h1>

In [74]:
#from モジュール名 import クラス名（もしくは関数名や変数名）
import pandas as pd
from pandas import DataFrame
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#matplotlibをinlineで表示するためのおまじない (plt.show()しなくていい)
%matplotlib inline

In [75]:
# titanic data csvファイルの読み込み
titanic_df = pd.read_csv('../data/titanic_train.csv')

In [76]:
# ファイルの先頭部を表示し、データセットを確認する
titanic_df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

<h1>1. ロジスティック回帰</h1>
<h3>不要なデータの削除・欠損値の補完</h3>

In [77]:
#予測に不要と考えるからうをドロップ (本当はここの情報もしっかり使うべきだと思っています)
titanic_df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

#一部カラムをドロップしたデータを表示
titanic_df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [79]:
#nullを含んでいる行を表示
titanic_df[titanic_df.isnull().any(1)].head(10)

Survived  Pclass     Sex  Age  SibSp  Parch      Fare Embarked
5          0       3    male  NaN      0      0    8.4583        Q
17         1       2    male  NaN      0      0   13.0000        S
19         1       3  female  NaN      0      0    7.2250        C
26         0       3    male  NaN      0      0    7.2250        C
28         1       3  female  NaN      0      0    7.8792        Q
29         0       3    male  NaN      0      0    7.8958        S
31         1       1  female  NaN      1      0  146.5208        C
32         1       3  female  NaN      0      0    7.7500        Q
36         1       3    male  NaN      0      0    7.2292        C
42         0       3    male  NaN      0      0    7.8958        C

In [80]:
titanic_df.isnull().any()

Survived    False
Pclass      False
Sex         False
Age          True
SibSp       False
Parch       False
Fare        False
Embarked     True
dtype: bool

In [82]:
#Ageカラムのnullを中央値で補完

titanic_df['AgeFill'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())

#再度nullを含んでいる行を表示 (Ageのnullは補完されている)
titanic_df[titanic_df.isnull().any(1)]

#titanic_df.dtypes

Survived  Pclass     Sex  Age  SibSp  Parch     Fare Embarked    AgeFill
5           0       3    male  NaN      0      0   8.4583        Q  29.699118
17          1       2    male  NaN      0      0  13.0000        S  29.699118
19          1       3  female  NaN      0      0   7.2250        C  29.699118
26          0       3    male  NaN      0      0   7.2250        C  29.699118
28          1       3  female  NaN      0      0   7.8792        Q  29.699118
..        ...     ...     ...  ...    ...    ...      ...      ...        ...
859         0       3    male  NaN      0      0   7.2292        C  29.699118
863         0       3  female  NaN      8      2  69.5500        S  29.699118
868         0       3    male  NaN      0      0   9.5000        S  29.699118
878         0       3    male  NaN      0      0   7.8958        S  29.699118
888         0       3  female  NaN      1      2  23.4500        S  29.699118

[179 rows x 9 columns]

In [83]:
titanic_df.isnull().any()

Survived    False
Pclass      False
Sex         False
Age          True
SibSp       False
Parch       False
Fare        False
Embarked     True
AgeFill     False
dtype: bool

In [96]:
titanic_df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked', 'AgeFill'],
      dtype='object')

In [97]:
titanic_df['Gender'] = titanic_df['Sex'].map({'female': 0, 'male': 1}).astype(int)

In [98]:
titanic_df.head(3)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked  AgeFill  \
0         0       3    male  22.0      1      0   7.2500        S     22.0   
1         1       1  female  38.0      1      0  71.2833        C     38.0   
2         1       3  female  26.0      0      0   7.9250        S     26.0   

   Gender  
0       1  
1       0  
2       0

In [101]:
data2 = titanic_df.loc[:, ["AgeFill", "Gender"]].values

In [102]:
data2

array([[22.        ,  1.        ],
       [38.        ,  0.        ],
       [26.        ,  0.        ],
       ...,
       [29.69911765,  0.        ],
       [26.        ,  1.        ],
       [32.        ,  1.        ]])

In [103]:
#生死フラグのみのリストを作成
label2 =  titanic_df.loc[:,["Survived"]].values

In [104]:
model2 = LogisticRegression()

In [105]:
model2.fit(data2, label2)

LogisticRegression()

In [106]:
model2.predict([[10,1]])

array([0])

In [107]:
model2.predict_proba([[10,1]])

array([[0.78854934, 0.21145066]])

# 課題

In [110]:
# 年齢が30歳で男の乗客は生き残れるか？
model2.predict_proba([[30,1]])

array([[0.80668102, 0.19331898]])

In [111]:
model2.predict([[30,1]])

array([0])