In [1]:
import sys, os
sys.path.append(os.pardir)  # 親ディレクトリのファイルをインポートするための設定
import numpy as np
from common import functions

def print_vec(text, vec):
    print("*** " + text + " ***")
    print(vec)
    print("shape: " + str(vec.shape))
    print("")


In [25]:
# 順伝播（単層・単ユニット）

# 重み
W = np.array([[0.1], [0.2]])

## 試してみよう_配列の初期化
W_zeros = np.zeros(2).reshape(2,1)
W_ones = np.ones(2).reshape(2,1)
W_rand = np.random.rand(2).reshape(2,1)
W_randint = np.random.randint(5, size=(2)).reshape(2,1)

print_vec("重み", W)
print_vec("重み_zeros", W_zeros)
print_vec("重み_ones", W_ones)
print_vec("重み_rand", W_rand)
print_vec("重み_randint", W_randint)


# バイアス
b = np.array(0.5)

## 試してみよう_数値の初期化
b_rand = np.array(np.random.rand()) # 0~1のランダム数値
b_rand2 = np.array(np.random.rand() * 10 -5)  # -5~5のランダム数値

print_vec("バイアス", b)
print_vec("バイアス_rand", b_rand)
print_vec("バイアス_rand2", b_rand2)

# 入力値
x = np.array([2, 3])
print_vec("入力", x)


# 総入力
u = np.dot(x, W) + b
print_vec("総入力", u)

u_init = np.dot(x, W_rand) + b_rand
print_vec("総入力(パラメータ初期化あり)", u_init)

# 中間層出力
z = functions.relu(u)
print_vec("中間層出力", z)

z_init = functions.relu(u_init)
print_vec("中間層出力(パラメータ初期化あり)", z_init)


*** 重み ***
[[0.1]
 [0.2]]
shape: (2, 1)

*** 重み_zeros ***
[[0.]
 [0.]]
shape: (2, 1)

*** 重み_ones ***
[[1.]
 [1.]]
shape: (2, 1)

*** 重み_rand ***
[[0.34614026]
 [0.69874741]]
shape: (2, 1)

*** 重み_randint ***
[[2]
 [3]]
shape: (2, 1)

*** バイアス ***
0.5
shape: ()

*** バイアス_rand ***
0.1327836326519798
shape: ()

*** バイアス_rand2 ***
-3.971437953447823
shape: ()

*** 入力 ***
[2 3]
shape: (2,)

*** 総入力 ***
[1.3]
shape: (1,)

*** 総入力(パラメータ初期化あり) ***
[2.92130637]
shape: (1,)

*** 中間層出力 ***
[1.3]
shape: (1,)

*** 中間層出力(パラメータ初期化あり) ***
[2.92130637]
shape: (1,)



In [31]:
# 順伝播（単層・複数ユニット）

# 重み
W = np.array([
    [0.1, 0.2, 0.3,0], 
    [0.2, 0.3, 0.4, 0.5], 
    [0.3, 0.4, 0.5, 1],
])

## 試してみよう_配列の初期化
W_zeros = np.zeros((4,3)).reshape(3,4)
W_ones = np.ones((4,3)).reshape(3,4)
W_rand = np.random.rand(4,3).reshape(3,4)
W_randint = np.random.randint(5, size=(4,3)).reshape(3,4)

print_vec("重み", W)
print_vec("重み_zeros", W_zeros)
print_vec("重み_ones", W_ones)
print_vec("重み_rand", W_rand)
print_vec("重み_randint", W_randint)

# バイアス
b = np.array([0.1, 0.2, 0.3])
print_vec("バイアス", b)

# 入力値
x = np.array([1.0, 5.0, 2.0, -1.0])
print_vec("入力", x)

#  総入力
u = np.dot(W, x) + b
print_vec("総入力", u)

u_init = np.dot(W_ones, x) + b
print_vec("総入力(パラメータ初期化あり)", u_init)

# 中間層出力
z = functions.sigmoid(u)
print_vec("中間層出力", z)

z_init = functions.sigmoid(u_init)
print_vec("中間層出力(パラメータ初期化あり)", z_init)


*** 重み ***
[[0.1 0.2 0.3 0. ]
 [0.2 0.3 0.4 0.5]
 [0.3 0.4 0.5 1. ]]
shape: (3, 4)

*** 重み_zeros ***
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
shape: (3, 4)

*** 重み_ones ***
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
shape: (3, 4)

*** 重み_rand ***
[[0.29146352 0.81503905 0.22448834 0.81600743]
 [0.42890333 0.54637008 0.93490375 0.21146722]
 [0.27276063 0.43601658 0.11443616 0.98667663]]
shape: (3, 4)

*** 重み_randint ***
[[2 0 4 0]
 [2 3 0 3]
 [1 0 0 2]]
shape: (3, 4)

*** バイアス ***
[0.1 0.2 0.3]
shape: (3,)

*** 入力 ***
[ 1.  5.  2. -1.]
shape: (4,)

*** 総入力 ***
[1.8 2.2 2.6]
shape: (3,)

*** 総入力(パラメータ初期化あり) ***
[7.1 7.2 7.3]
shape: (3,)

*** 中間層出力 ***
[0.85814894 0.90024951 0.93086158]
shape: (3,)

*** 中間層出力(パラメータ初期化あり) ***
[0.99917558 0.99925397 0.99932492]
shape: (3,)



In [32]:
# 順伝播（3層・複数ユニット）

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")
    network = {}
    
    input_layer_size = 3
    hidden_layer_size_1=10
    hidden_layer_size_2=5
    output_layer_size = 4
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size_1)
    network['W2'] = np.random.rand(hidden_layer_size_1,hidden_layer_size_2)
    network['W3'] = np.random.rand(hidden_layer_size_2,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size_1)
    network['b2'] =  np.random.rand(hidden_layer_size_2)
    network['b3'] =  np.random.rand(output_layer_size)

    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("重み3", network['W3'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )
    print_vec("バイアス3", network['b3'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")

    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1
    
    # 1層の総出力
    z1 = functions.relu(u1)
    
    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 2層の総出力
    z2 = functions.relu(u2)

    # 出力層の総入力
    u3 = np.dot(z2, W3) + b3
    
    # 出力層の総出力
    y = u3
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("中間層出力2", z2)
    print_vec("総入力2", u2)
    print_vec("出力", y)
    print("出力合計: " + str(np.sum(y)))

    return y, z1, z2

# 入力値
x = np.array([1., 2., 4.])
print_vec("入力", x)

# ネットワークの初期化
network =  init_network()

y, z1, z2 = forward(network, x)

*** 入力 ***
[1. 2. 4.]
shape: (3,)

##### ネットワークの初期化 #####
*** 重み1 ***
[[0.10179338 0.78088894 0.35323861 0.4927603  0.84222227 0.32886649
  0.17036739 0.9221994  0.47890072 0.32115778]
 [0.91400001 0.83058733 0.23966356 0.38865621 0.94014713 0.83541307
  0.73500563 0.28121797 0.07723456 0.38808084]
 [0.32865167 0.48385891 0.04804262 0.09113071 0.94303354 0.50377092
  0.26165245 0.17512273 0.61981733 0.33591445]]
shape: (3, 10)

*** 重み2 ***
[[0.77831667 0.95383272 0.1236307  0.64887917 0.29995767]
 [0.46074122 0.66967321 0.0389459  0.06745527 0.97199282]
 [0.32410086 0.65209006 0.6491758  0.87781537 0.52673197]
 [0.95439963 0.02535558 0.45136357 0.67306802 0.66289148]
 [0.62257061 0.47330524 0.83667276 0.63142609 0.37045322]
 [0.09175539 0.70488524 0.33596632 0.08910016 0.43573269]
 [0.80443599 0.77200076 0.89891072 0.12323864 0.46438185]
 [0.5591261  0.70931267 0.39967646 0.44655224 0.79121189]
 [0.32589481 0.1294294  0.78644722 0.9558662  0.20172554]
 [0.51510287 0.42890056 0.13826858

In [5]:
np.random.rand(3, 3)

array([[0.97412186, 0.36938662, 0.50517416],
       [0.03953528, 0.77026516, 0.8817622 ],
       [0.14733796, 0.31482736, 0.33081122]])

In [6]:
# 多クラス分類
# 2-3-4ネットワーク

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    
    input_layer_size = 3
    hidden_layer_size=50
    output_layer_size = 6
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
    network['W2'] = np.random.rand(hidden_layer_size,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size)
    network['b2'] =  np.random.rand(output_layer_size)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 出力値
    y = functions.softmax(u2)
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
        
    return y, z1

## 事前データ
# 入力値
x = np.array([1., 2.,  3.])

# 目標出力
d = np.array([0, 0, 0, 1, 0, 0])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("交差エントロピー誤差",  loss)



##### ネットワークの初期化 #####
*** 重み1 ***
[[0.1692205  0.06497633 0.8304818  0.10219473 0.42728008 0.05361395
  0.72870888 0.63549261 0.74759942 0.40415317 0.04425458 0.96205355
  0.59949181 0.27334498 0.63996353 0.060263   0.33924374 0.28336771
  0.67801639 0.4623586  0.65492675 0.38588477 0.03474399 0.0143269
  0.26837342 0.46774364 0.62197953 0.40728384 0.12117668 0.91246995
  0.02293698 0.62290258 0.20587484 0.73461621 0.98495168 0.22451427
  0.01908655 0.63760327 0.58873469 0.16088952 0.87811133 0.36815914
  0.34720002 0.7694625  0.78813178 0.03789177 0.16242312 0.39563617
  0.09448206 0.90561492]
 [0.96499345 0.84917084 0.65551451 0.317136   0.92454526 0.29781861
  0.5330817  0.40393111 0.1632953  0.98213507 0.84235632 0.58926962
  0.51984875 0.52362039 0.94541759 0.9278616  0.88688986 0.89136085
  0.38533468 0.87277513 0.49586602 0.45822771 0.51769015 0.62699689
  0.89173858 0.32338612 0.53637972 0.43999947 0.47440575 0.21052394
  0.66615643 0.64362422 0.67259719 0.57928    0.4278816  

In [33]:
# 多クラス分類
# ！試してみよう_ノードの構成を 3-5-6 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成

    network = {}
    
    input_layer_size = 3
    hidden_layer_size= 5
    output_layer_size = 6
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
    network['W2'] = np.random.rand(hidden_layer_size,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size)
    network['b2'] =  np.random.rand(output_layer_size)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 出力値
    y = functions.softmax(u2)
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
        
    return y, z1

## 事前データ
# 入力値
x = np.array([1., 2.,  3.])

# 目標出力
d = np.array([0, 0, 0, 1, 0, 0])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("交差エントロピー誤差",  loss)



##### ネットワークの初期化 #####
*** 重み1 ***
[[0.89037629 0.28367084 0.636005   0.62058245 0.91945823]
 [0.96677806 0.46625668 0.74371382 0.84251901 0.21178256]
 [0.27052406 0.654497   0.83210334 0.44767618 0.3245026 ]]
shape: (3, 5)

*** 重み2 ***
[[0.87799888 0.24848994 0.24168207 0.09119614 0.39116809 0.37241803]
 [0.26797951 0.16965768 0.07764997 0.18122146 0.34532456 0.20097807]
 [0.47017577 0.90237578 0.09247147 0.1169564  0.50422511 0.43165394]
 [0.50485963 0.49106176 0.15014352 0.69240163 0.49039209 0.19138532]
 [0.99567832 0.96359864 0.40108014 0.68046533 0.42130007 0.75858453]]
shape: (5, 6)

*** バイアス1 ***
[0.61083234 0.23435654 0.99801627 0.37051114 0.74004757]
shape: (5,)

*** バイアス2 ***
[0.89732469 0.22767655 0.60728867 0.59719243 0.01941539 0.53830024]
shape: (6,)

##### 順伝播開始 #####
*** 総入力1 ***
[4.24633693 3.41403174 5.61775893 4.01916015 3.05657873]
shape: (5,)

*** 中間層出力1 ***
[4.24633693 3.41403174 5.61775893 4.01916015 3.05657873]
shape: (5,)

*** 総入力2 ***
[13.25430935 11.85036585

hidden_layerのノード数を50→5に変更したことで、交差エントロピー誤差が15.36->6.37に減少

In [7]:
# 回帰
# 2-3-2ネットワーク

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    input_layer_size = 3
    hidden_layer_size=50
    output_layer_size = 2
    
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
    network['W2'] = np.random.rand(hidden_layer_size,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size)
    network['b2'] =  np.random.rand(output_layer_size)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = u2
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
    
    return y, z1

# 入力値
x = np.array([1., 2., 3.])
network =  init_network()
y, z1 = forward(network, x)
# 目標出力
d = np.array([2., 4.])
# 誤差
loss = functions.mean_squared_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("二乗誤差",  loss)


##### ネットワークの初期化 #####
*** 重み1 ***
[[0.54474589 0.76495946 0.82481487 0.2665464  0.08555805 0.27961012
  0.11622711 0.09854697 0.35815205 0.94716328 0.06396586 0.78156411
  0.29486138 0.6881851  0.87239752 0.05497582 0.7349415  0.31019922
  0.21112434 0.28611649 0.253549   0.99187192 0.38166391 0.04081456
  0.3623924  0.64287686 0.80229584 0.32890354 0.46229437 0.65397364
  0.37186143 0.79394268 0.39191176 0.97430978 0.98110054 0.45239164
  0.97000127 0.66355895 0.50317618 0.41860623 0.56304395 0.16266522
  0.25336726 0.79676131 0.40275489 0.29935365 0.75331882 0.6154854
  0.96742689 0.61858411]
 [0.47080544 0.40211234 0.44909527 0.06046966 0.83898208 0.54423432
  0.59458608 0.39914508 0.87286337 0.6801306  0.24433355 0.67082796
  0.17257814 0.26772929 0.91397518 0.48665458 0.59636115 0.93151925
  0.52075674 0.23951505 0.29344769 0.15821978 0.31725376 0.32301295
  0.71313469 0.39174703 0.93495704 0.25728097 0.74945201 0.70149684
  0.01573497 0.70656719 0.5640777  0.73809769 0.95705893 

In [40]:
# 回帰
# 2-3-2ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    input_layer_size = 3
    hidden_layer_size= 5
    output_layer_size = 4
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    network['W1'] = np.random.rand(input_layer_size, hidden_layer_size)
    network['W2'] = np.random.rand(hidden_layer_size,output_layer_size)

    network['b1'] =  np.random.rand(hidden_layer_size)
    network['b2'] =  np.random.rand(output_layer_size)
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = u2
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
    
    return y, z1

# 入力値
x = np.array([1., 2., 3.])
network =  init_network()
y, z1 = forward(network, x)
# 目標出力
d = np.array([2., 4., 6., 8.]) #dは適当に要素を増やした

print_vec("y", y)
print_vec("d", d)

# 誤差
loss = functions.mean_squared_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("二乗誤差",  loss)


##### ネットワークの初期化 #####
*** 重み1 ***
[[0.27743374 0.97179817 0.44012312 0.76284619 0.75737834]
 [0.94410176 0.89395561 0.85731575 0.08745518 0.05171122]
 [0.1117724  0.84101817 0.16538401 0.31794668 0.30315632]]
shape: (3, 5)

*** 重み2 ***
[[0.02337196 0.44477342 0.30412064 0.28497536]
 [0.84536265 0.87125435 0.02042739 0.07314368]
 [0.32089209 0.74125269 0.70655289 0.51157824]
 [0.21885947 0.24071684 0.70886705 0.36948755]
 [0.60622801 0.72633175 0.11628846 0.42552909]]
shape: (5, 4)

*** バイアス1 ***
[0.76825129 0.38210379 0.79336253 0.65159374 0.48208674]
shape: (5,)

*** バイアス2 ***
[0.19393516 0.00806191 0.73862013 0.05558941]
shape: (4,)

##### 順伝播開始 #####
*** 総入力1 ***
[3.26920574 5.66486768 3.44426917 2.54319033 2.25235646]
shape: (5,)

*** 中間層出力1 ***
[3.26920574 5.66486768 3.44426917 2.54319033 2.25235646]
shape: (5,)

*** 総入力2 ***
[ 8.08649211 11.19887882  6.34683675  5.0617153 ]
shape: (4,)

*** 出力1 ***
[ 8.08649211 11.19887882  6.34683675  5.0617153 ]
shape: (4,)

出力合計: 30.693922982

In [43]:
# 2値分類
# 2-3-1ネットワーク
# ！試してみよう_ノードの構成を 5-10-20-1 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    #各層のノード数を下記のWの重み初期化時に決めている様子
    network['W1'] = np.array([
        [0.1, 0.3, 0.5, 0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5, 0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5, 0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5, 0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1],
        [0.1, 0.3, 0.5, 0.1, 0.3, 0.5,0.1, 0.3, 0.5, 0.1]
    ])
    network['W2'] = np.random.rand(10, 20)
    network['W3'] = np.random.rand(20, 1)

    network['b1'] = np.random.rand(10)
    network['b2'] =np.random.rand(20)
    network['b3'] =np.random.rand(1)

    return network


# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2, W3 = network['W1'], network['W2'],network['W3']
    b1, b2, b3 = network['b1'], network['b2'],network['b3']

    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層1の総出力
    z1 = functions.relu(u1)
    # 隠れ層２層への総入力
    u2 = np.dot(z1, W2) + b2
    # 隠れ層2の出力
    z2 = functions.relu(u2)
    
    u3 = np.dot(z2, W3) + b3
    z3 = functions.sigmoid(u3)
    y = z3    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))

    return y, z1

# 入力値
x = np.array([1., 2.,2.,4.,5.])

# 目標出力
d = np.array([1])
network =  init_network()
y, z1 = forward(network, x)
# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("交差エントロピー誤差",  loss)

##### ネットワークの初期化 #####
##### 順伝播開始 #####
*** 総入力1 ***
[1.98271707 4.53815495 7.76286934 1.56383982 4.95036139 7.35621049
 1.73248926 5.01681669 7.5455995  1.79008322]
shape: (10,)

*** 中間層出力1 ***
[1.98271707 4.53815495 7.76286934 1.56383982 4.95036139 7.35621049
 1.73248926 5.01681669 7.5455995  1.79008322]
shape: (10,)

*** 総入力2 ***
[25.11641338 24.8143866  23.26415499 15.46568854 26.45741527 22.19844931
 24.26360322 20.7066189  16.60870589 29.3380304  24.51104205 12.86829008
 13.74272659 26.20305597 21.42646244 29.85780545 22.40771861 24.23543726
 17.5572929  32.51869606]
shape: (20,)

*** 出力1 ***
[1.]
shape: (1,)

出力合計: 1.0

##### 結果表示 #####
*** 中間層出力 ***
[1.98271707 4.53815495 7.76286934 1.56383982 4.95036139 7.35621049
 1.73248926 5.01681669 7.5455995  1.79008322]
shape: (10,)

*** 出力 ***
[1.]
shape: (1,)

*** 訓練データ ***
[1]
shape: (1,)

*** 交差エントロピー誤差 ***
-9.999999505838704e-08
shape: ()

